theme: osuny
_merge: deep
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: true
    positions:
      - primary
      - footer
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  home:
    head:
      title: site
  persons:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: true
  projects:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: true
      options:
        year: true
    share_links:
      enabled: true
      facebook: true
      linkedin: true
      twitter: true
  posts:
    index:
      options:
        categories: false
    single:
      options:
        reading_time: false
        updated_at: false
    share_links:
      enabled: true
      facebook: true
      linkedin: true
      twitter: true
  image_sizes:
    _default:
      layouts:
        list:
          mobile:   360
          tablet:   555
          desktop:  864
        grid:
          desktop:  864